In [1]:
def square(n):
    for i in range(3):
        yield i**2

In [2]:
square(3)

<generator object square at 0x00000250DA1365A0>

In [3]:
for i in square(3):
    print(i)


0
1
4


In [4]:
def my_generator():
    yield 1
    yield 2
    yield 3

In [22]:
gen=my_generator()
gen

<generator object my_generator at 0x00000250DA76A2A0>

In [23]:
next(gen)

1

In [24]:
for val in gen:
    print(val)


2
3


In [25]:
##Practical : reading large files

def read_large_file(file_path):
    with open(file_path,'r') as file:
        for line in file:
            yield line

In [26]:
file_path='large_file.txt'

for line in read_large_file(file_path):
    print(line.strip())


ulletproof Boy Scouts), also known as the Bangtan Boys, is a South Korean boy band formed in 2010. The band consists of Jin, Suga, J-Hope, RM, Jimin, V, and Jungkook, who co-write or co-produce much of their material. Originally a hip hop group, they expanded their musical style to incorporate a wide range of genres, while their lyrics have focused on subjects including mental health, the troubles of school-age youth and coming of age, loss, the journey towards self-love, individualism, and the consequences of fame and recognition. Their discography and adjacent work has also referenced literature, philosophy and psychology, and includes an alternate universe storyline.


In [27]:
##function copy
def welcome():
    return "Welcome to the advance python course!"

welcome()

'Welcome to the advance python course!'

In [28]:
wel=welcome
print(wel())
del welcome
print(wel())

Welcome to the advance python course!
Welcome to the advance python course!


In [ ]:
##closures

def main_welcome(msg):
    #msg='Welcome'
    def sub_welcome_method():
        print("Welcome to the advance python course.")
        print(msg)
        print("Please learn these concepts properly.")
    return sub_welcome_method()

In [37]:
main_welcome("Welcome everyone.")

Welcome to the advance python course.
Welcome everyone.
Please learn these concepts properly.


In [38]:
#Decorator

def main_welcome(func):
    #msg='Welcome'
    def sub_welcome_method():
        print("Welcome to the advance python course.")
        func()
        print("Please learn these concepts properly.")
    return sub_welcome_method()

In [39]:
def course_introduction():
    print("This is a advanced python course.")

course_introduction()

This is a advanced python course.


In [40]:
main_welcome(course_introduction)

Welcome to the advance python course.
This is a advanced python course.
Please learn these concepts properly.


In [41]:
@main_welcome
def course_introduction():
    print("This is an advanced python course.")

Welcome to the advance python course.
This is an advanced python course.
Please learn these concepts properly.


In [42]:
#Decorators with arguments

def repeat(n):
    def decorator(func):
        def wrapper(*args,**kwargs):
            for _ in range(n):
                func(*args,**kwargs)
        return wrapper
    return decorator

In [43]:
@repeat(3)
def say_hello():
    print("Hello")

In [44]:
say_hello()

Hello
Hello
Hello


In [45]:
pip install numpy

  Using cached numpy-2.2.2-cp313-cp313-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.2.2-cp313-cp313-win_amd64.whl (12.6 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [47]:
import numpy as np

##create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [49]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) #1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [51]:
#2D array

arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [53]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [54]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
##identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
#Numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#Element wise addition
print("Addition:",arr1+arr2)

#Element wise subtraction
print("Substraction:",arr1-arr2)

print("Multiplication:",arr1*arr2)

print("Division:",arr1/arr2)



Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [57]:
#Universal functions
arr=np.array([2,3,4,5,6])
#sqaure root
print(np.sqrt(arr))
#exponential
print(np.exp(arr))
#sine
print(np.sin(arr))
#natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [59]:
#array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [63]:
arr[0][0]

np.int64(1)

In [64]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [66]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [72]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [73]:
#Modify element
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [75]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [78]:
#statistical concepts-normalization
#to have a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])

#calculate the mean and standard deviation 
mean=np.mean(data)
std_dev=np.std(data)

#Normalize the data
normalized_data=(data-mean)/std_dev
print("Normalized data:",normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


np.mean
np.median
np.std
np.var

In [84]:
#Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [85]:
pip install pandas

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.5 MB 602.0 kB/s eta 0:00:19
   -- ------------------------------------- 0.8/11.5 MB 759.7 kB/s eta 0:00:15
   --- ------------------------------------ 1.0/11.5 MB 855.2 kB/s eta 0:00:13
   ---- ----------------------------------- 1.3/11.5 MB 879.4 kB/s eta 0:00:12
   ----- ---------------------------------- 1.6/11.5 MB 906.1 kB/s eta 0:00:11
   ------ --------------------------------- 1.8/11.5 MB 896.6 kB/s eta 0:00:11
   -------- ------------------------------- 2.4/11.5 MB 1.1 MB/s eta 0:00:09
   --------- ------------------------------ 2.6/11.5 MB 1.1 MB/s eta 0:00:09
   ---------- ----------------------------- 2.9/11.5 MB 1.1 MB/s eta 0:00:08
   ---------- -


[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [86]:
import pandas as pd

In [89]:
import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series 
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [90]:
#Create a series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64


In [91]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

Data Frame is having multiple rows and columns.

In [95]:
#Data frame
#create a dataframe from a dictionary of list

data={
    'Name':['Krish','John','Jack'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','FLorida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    FLorida
<class 'pandas.core.frame.DataFrame'>


In [96]:
#Create a data file from a list of dictionaries
data=[
    {'Name':'Krish','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Goa'},
    {'Name':'Jack','Age':36,'City':'London'}
]
df=pd.DataFrame(data)
print(df)
print(type(df))


    Name  Age       City
0  Krish   32  Bangalore
1   John   34        Goa
2   Jack   36     London
<class 'pandas.core.frame.DataFrame'>


In [99]:
#Accessing data from dataframe
df

Name  Age       City
0  Krish   32  Bangalore
1   John   34        Goa
2   Jack   36     London

In [100]:
df['Name']

0    Krish
1     John
2     Jack
Name: Name, dtype: object

In [101]:
type(df['Name'])

pandas.core.series.Series

In [102]:
df.loc[0]

Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In [103]:
df.iloc[0]

Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In [104]:
df.iloc[0][1]

C:\Users\admin\AppData\Local\Temp\ipykernel_115632\2309508539.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]


np.int64(32)

In [105]:
df['Salary']=[50000,60000,70000]

In [106]:
df

Name  Age       City  Salary
0  Krish   32  Bangalore   50000
1   John   34        Goa   60000
2   Jack   36     London   70000

In [107]:
df.drop('Salary',axis=1)

Name  Age       City
0  Krish   32  Bangalore
1   John   34        Goa
2   Jack   36     London

In [108]:
df

Name  Age       City  Salary
0  Krish   32  Bangalore   50000
1   John   34        Goa   60000
2   Jack   36     London   70000

drop is for temporary deletion

In [109]:
df.drop('Salary',axis=1,inplace=True)

In [110]:
df

Name  Age       City
0  Krish   32  Bangalore
1   John   34        Goa
2   Jack   36     London

In [111]:
#add age to the column
df['Age']=df['Age']+1
df

Name  Age       City
0  Krish   33  Bangalore
1   John   35        Goa
2   Jack   37     London

In [112]:
df.drop(0)

Name  Age    City
1  John   35     Goa
2  Jack   37  London

In [113]:
df.describe()

Age
count   3.0
mean   35.0
std     2.0
min    33.0
25%    34.0
50%    35.0
75%    36.0
max    37.0